services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'enem_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - enem_db:/var/lib/mysql

volumes:
  enem_db: